In [1]:
import pandas as pd

train = pd.read_csv("../data/raw/train.csv")
test = pd.read_csv("../data/raw/test.csv")
sample_out = pd.read_csv("../data/raw/sample_test_out.csv")

print("train:", train.shape)
print("test:", test.shape)
print(train.columns.tolist())
train.head()

train: (75000, 4)
test: (75000, 3)
['sample_id', 'catalog_content', 'image_link', 'price']

,sample_id,catalog_content,image_link,price
0,33127,"Item Name: La Victoria Green Taco Sauce Mild, ...",https://m.media-amazon.com/images/I/51mo8htwTH...,4.89
1,198967,"Item Name: Salerno Cookies, The Original Butte...",https://m.media-amazon.com/images/I/71YtriIHAA...,13.12
2,261251,"Item Name: Bear Creek Hearty Soup Bowl, Creamy...",https://m.media-amazon.com/images/I/51+PFEe-w-...,1.97
3,55858,Item Name: Judee’s Blue Cheese Powder 11.25 oz...,https://m.media-amazon.com/images/I/41mu0HAToD...,30.34
4,292686,"Item Name: kedem Sherry Cooking Wine, 12.7 Oun...",https://m.media-amazon.com/images/I/41sA037+Qv...,66.49

In [2]:
sample_out.head()

   sample_id      price
0     217392  62.080008
1     209156  17.189763
2     262333  96.501410
3     295979   5.652474
4      50604  23.794780